version: '3'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama_app
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: always
    networks:
      - lahatrad_network

networks:
  lahatrad_network:
